name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: linux
            arch: amd64
          - os: windows
            arch: amd64

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        if [ "${{ matrix.os }}" = "windows" ]; then
          go build -ldflags="-s -w" -o spiral.exe main.go
          mv spiral.exe spiral-${{ matrix.os }}-${{ matrix.arch }}.exe
        else
          go build -ldflags="-s -w" -o spiral main.go
          chmod +x spiral
          mv spiral spiral-${{ matrix.os }}-${{ matrix.arch }}
        fi
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: spiral-${{ matrix.os }}-${{ matrix.arch }}*
        generate_release_notes: true 